### ISSUE TITLE
IMU calibration

### ISSUE THREAD

**Issue by ouyangandy** [InvenSenseInc/public.MA_Lite.linux_driver#1]
i want to get internal reference(drift etc.),how can i get this?

**Comment by jmaneyrol-invn** [comment]
Hello,
you can have all sensors datasheets on our website:
https://www.invensense.com

All specs are described here.

**Comment by ouyangandy** [comment]
I am from a Chinese company. The IMU used in one of the products we developed is IAM-20680HP. In order to ensure the accuracy, I want to get its factory parameters(like Zero drift;misalignment matrix;
scale matrix;) instead of calibrating it myself, but I can hardly find it on the website you provide. Can you help me?

**Comment by jmaneyrol-invn** [comment]
Here is the web page for this product:
https://www.invensense.com/products/motion-tracking/6-axis/iam-20680/

Here is the datasheet:
http://www.invensense.com/download-pdf/iam-20680-datasheet/

Sensors specs are inside if required.
