### ISSUE TITLE
ICM20648 Support

### ISSUE THREAD

**Issue by NullandKale** [InvenSenseInc/public.MA_Lite.linux_driver#2]
ICM20648 support does not seem to work. [This](https://gist.github.com/NullandKale/0cddca386158aed5f2a533064deebc82) is the error that happens when you try and compile. After looking at the make file it seems like a few folders are missing.

**Comment by jmaneyrol-invn** [comment]
Hello,
only IAM20680 is supported by this driver for the moment.
All the files for the other chips are not provided.

**Comment by NullandKale** [comment]
Could you point me to the driver for the ICM20648. The documentation claims it exists, but it is not available in the InvenSenseInc Github. I've checked with the documentation [here](https://www.invensense.com/products/motion-tracking/6-axis/icm-20648/), and in the Invensense dev corner.

**Comment by Motirn** [comment]
> Hello,
> only IAM20680 is supported by this driver for the moment.
> All the files for the other chips are not provided.

Hi, How/where can I get access to the ICM20648/ICM20948 files. we are developing a product based on ICM20948. spec sheet for ICM20698 describes the software drivers fully compatible with Android/Linux, but I could not find the drivers available anywhere..!

**Comment by pxc2017** [comment]
> Hello,
> only IAM20680 is supported by this driver for the moment.
> All the files for the other chips are not provided.

hello could you please tell me how to use this package to get measurement from iam-20860 in linux?and is IAM-20860 calibrated in factory?

**Comment by aworms-moba** [comment]
Hi, 
we're also developing a product based on the ICM20948. 
This here seems to be the only source for Linux/Android device drivers we could find so far.
So hoefully you can help us.
Do the ICM20648/ICM20948 device drivers and HAL for Linux/Android, mentioned in the spec and here in the device tree example (README), exist and where/how can we get access to them?
Thanks in advance.

**Comment by jmaneyrol-invn** [comment]
> Hi,
> we're also developing a product based on the ICM20948.
> This here seems to be the only source for Linux/Android device drivers we could find so far.
> So hoefully you can help us.
> Do the ICM20648/ICM20948 device drivers and HAL for Linux/Android, mentioned in the spec and here in the device tree example (README), exist and where/how can we get access to them?
> Thanks in advance.

Hello,
please contact our technical support at the following address: techsupport_Europe@invensense.com

Thanks for your interest.

**Comment by msandstedt** [comment]
> > Hi,
> > we're also developing a product based on the ICM20948.
> > This here seems to be the only source for Linux/Android device drivers we could find so far.
> > So hoefully you can help us.
> > Do the ICM20648/ICM20948 device drivers and HAL for Linux/Android, mentioned in the spec and here in the device tree example (README), exist and where/how can we get access to them?
> > Thanks in advance.
> 
> Hello, please contact our technical support at the following address: [techsupport_Europe@invensense.com](mailto:techsupport_Europe@invensense.com)
> 
> Thanks for your interest.

I am in the same boat on a product I work with.  The above email address no longer exists.  I am attempting to register for support here:

https://invensense.tdk.com/developers/login/?message=support&redirect_to=support

However, registration is disabled:

![ivensense-support-registration-unavailable](https://github.com/InvenSenseInc/public.MA_Lite.linux_driver/assets/5436999/27bc7247-8e79-46e2-8f8f-d94f5b15a57e)

Where do we go to get drivers for the ICM20648 and ICM20948?
