### ISSUE TITLE
IAM-20860

### ISSUE THREAD

**Issue by pxc2017** [InvenSenseInc/public.MA_Lite.linux_driver#3]
hello i got an IAM-20860 and wanna use it in linux,how to use this package to dirve iam-20860 in linux,and is this chip calibrated in factory? if not,how should i calilbrate it to get bias or scale error or axis rotation error of two sensors? thank you

**Comment by jmaneyrol-invn** [comment]
Hello,

this linux driver is supporting a wide range a Linux kernel. Follow the instructions inside README file to know how to integrate it inside Linux sources.

For using the driver from userspace, you can have a look at tool test-sensors-sysfs located inside [public.MA_Lite.android_hal_sensors](https://github.com/InvenSenseInc/public.MA_Lite.android_sensors_hal/tree/master/iam20680/sensors/linux/test-sensors-sysfs) repository. Inside directory iam20680/sensors/linux/test-sensors-sysfs.

Best regards,
JB
